---
# Configuración de Seguridad
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appwrite-sa
  namespace: appwrite
  annotations:
    serviceaccount.openshift.io/automount-service-account-token: "true"

---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: appwrite-scc
  #namespace: appwrite
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
  - system:serviceaccount:appwrite:appwrite-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appwrite-scc-role
  #namespace: appwrite
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
    resourceNames: ["appwrite-scc"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appwrite-scc-binding
  #namespace: appwrite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appwrite-scc-role
subjects:
  - kind: ServiceAccount
    name: appwrite-sa
    namespace: appwrite

---
# Base de Datos MariaDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-mariadb
  namespace: appwrite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appwrite-mariadb
  template:
    metadata:
      labels:
        app: appwrite-mariadb
    spec:
      serviceAccountName: appwrite-sa
      containers:
        - name: mariadb
          image: mariadb:10.11
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: appwrite
            - name: MYSQL_USER
              value: appwrite
            - name: MYSQL_PASSWORD
              value: appwrite
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: appwrite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# Redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-redis
  namespace: appwrite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appwrite-redis
  template:
    metadata:
      labels:
        app: appwrite-redis
    spec:
      serviceAccountName: appwrite-sa
      containers:
        - name: redis
          image: redis:7.2.4-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: appwrite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
# Docker-in-Docker (DinD)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-dind
  namespace: appwrite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appwrite-dind
  template:
    metadata:
      labels:
        app: appwrite-dind
    spec:
      serviceAccountName: appwrite-sa
      containers:
        - name: dind
          image: docker:dind
          securityContext:
            privileged: true
          args:
            - "--tls=false"
            - "-H"
            - "tcp://0.0.0.0:2375"
            - "-H"
            - "unix:///var/run/docker.sock"
          volumeMounts:
            - name: dind-socket
              mountPath: /var/run
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - 70-85-c2-d5-f0-c0 # Mismo nodo que el PV
      volumes:
        - name: dind-socket
          persistentVolumeClaim:
            claimName: dind-socket-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dind-socket-pv
  #namespace: appwrite
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/local-storage/appwrite/docker # Ruta en el nodo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 70-85-c2-d5-f0-c0 # Especifica el nodo donde está el directorio

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  #namespace: appwrite
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-socket-pvc
  namespace: appwrite
spec:
  accessModes:
    - ReadWriteOnce  # TODO ReadWriteMany Importante!
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi

---
# Appwrite Core
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-main
  namespace: appwrite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appwrite-main
  template:
    metadata:
      labels:
        app: appwrite-main
    spec:
      serviceAccountName: appwrite-sa
      initContainers:
        - name: wait-for-dependencies
          image: busybox
          command: ['sh', '-c', 'until nc -z appwrite-mariadb 3306 && nc -z appwrite-redis 6379 && nc -z appwrite-dind 2375; do echo "Waiting..."; sleep 2; done;']
      containers:
        - name: traefik
          image: traefik:2.11
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
          volumeMounts:
            - name: dind-socket
              mountPath: /var/run/docker.sock
          env:
            - name: TRAEFIK_API_DASHBOARD
              value: "true"
            - name: TRAEFIK_API_INSECURE
              value: "true"
            - name: TRAEFIK_PROVIDERS_DOCKER_ENDPOINT
              value: unix:///var/run/docker.sock
            - name: TRAEFIK_PROVIDERS_DOCKER_SWARMMODE
              value: "true"
        - name: appwrite
          image: appwrite/appwrite:1.6.0
          envFrom:  # Usar el ConfigMap
            - configMapRef:
                name: appwrite-env
          ports:
            - containerPort: 9501
          volumeMounts:
            - name: appwrite-storage
              mountPath: /storage
            - name: dind-socket
              mountPath: /var/run/docker.sock
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - 70-85-c2-d5-f0-c0 # Mismo nodo que el PV
      volumes:
        - name: dind-socket
          persistentVolumeClaim:
            claimName: dind-socket-pvc
        - name: appwrite-storage
          persistentVolumeClaim:
            claimName: appwrite-pvc

---
# Volumen para Appwrite
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appwrite-pvc
  namespace: appwrite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: appwrite-admin-service
  namespace: appwrite
spec:
  ports:
    - name: admin
      port: 9501
      targetPort: 9501
  selector:
    app: appwrite-main

---
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: appwrite-admin
  namespace: appwrite
spec:
  port:
    targetPort: admin
  to:
    kind: Service
    name: appwrite-admin-service

---
# Workers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-workers
  namespace: appwrite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appwrite-workers
  template:
    metadata:
      labels:
        app: appwrite-workers
    spec:
      serviceAccountName: appwrite-sa
      containers:
        - name: worker-audits
          image: appwrite/appwrite:1.6.0
          command: ["worker-audits"]
          envFrom:
            - configMapRef:
                name: appwrite-env

        - name: worker-webhooks
          image: appwrite/appwrite:1.6.0
          command: ["worker-webhooks"]
          envFrom:
            - configMapRef:
                name: appwrite-env

      # Agregar más workers según necesidad

---
# OpenRuntimes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-openruntimes
  namespace: appwrite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appwrite-openruntimes
  template:
    metadata:
      labels:
        app: appwrite-openruntimes
    spec:
      serviceAccountName: appwrite-sa
      containers:
        - name: executor
          image: openruntimes/executor:0.6.29
          volumeMounts:
            - name: dind-socket
              mountPath: /var/run/docker.sock
        - name: proxy
          image: openruntimes/proxy:0.6.3
          ports:
            - containerPort: 3000
              name: runtime-http
            - containerPort: 3001
              name: runtime-https
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - 70-85-c2-d5-f0-c0 # Mismo nodo que el PV
      volumes:
        - name: dind-socket
          persistentVolumeClaim:
            claimName: dind-socket-pvc

---
# Servicios
apiVersion: v1
kind: Service
metadata:
  name: appwrite-service
  namespace: appwrite
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
  selector:
    app: appwrite-main

---
apiVersion: v1
kind: Service
metadata:
  name: openruntimes-service
  namespace: appwrite
spec:
  ports:
    - name: runtime-http
      port: 3000
      targetPort: 3000
    - name: runtime-https
      port: 3001
      targetPort: 3001
  selector:
    app: appwrite-openruntimes

---
# Configuración de Rutas
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: appwrite-http
  namespace: appwrite
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: appwrite-service

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: appwrite-https
  namespace: appwrite
spec:
  port:
    targetPort: https
  to:
    kind: Service
    name: appwrite-service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openruntimes-http
  namespace: appwrite
spec:
  port:
    targetPort: runtime-http
  to:
    kind: Service
    name: openruntimes-service

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openruntimes-https
  namespace: appwrite
spec:
  port:
    targetPort: runtime-https
  to:
    kind: Service
    name: openruntimes-service
  tls:
    termination: edge

---
# ConfigMap para variables compartidas
apiVersion: v1
kind: ConfigMap
metadata:
  name: appwrite-env
  namespace: appwrite
data:
  _APP_ENV: "development"
  _APP_DB_HOST: "appwrite-mariadb"
  _APP_DB_PORT: "3306"
  _APP_DB_USER: "appwrite"
  _APP_DB_PASS: "appwrite"
  _APP_REDIS_HOST: "appwrite-redis"
  _APP_REDIS_PORT: "6379"
  # TODO NO ES SEGURO _APP_CONSOLE_PORT: "9501"

# ONECLICK INSTALLATION
#   oc apply -f deployment.yml

# NOTAS:
# No hay resource requests/limits adecuada para Appwrite
# No hay liveness/readiness probes
# Exposición del puerto 9501 (UI de administración)
# Mapeo de puertos para OpenRuntimes (ej: 3000-3001)
# NODE TERMINAL:
# mkdir -p /mnt/local-storage/appwrite/docker
# chmod 777 /mnt/local-storage/appwrite/docker